apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: dnowell-dnowell-poi-gateway-app-dev
  annotations:
    argocd/app-name: dnowell-dnowell-poi-gateway-app-dev
    backstage.io/kubernetes-id: dnowell-dnowell-poi-gateway-app-dev
    backstage.io/kubernetes-namespace: dnowell
    backstage.io/kubernetes-label-selector: 'app.kubernetes.io/instance=dnowell-dnowell-poi-gateway-app-dev'
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: Summit23Janus1/dnowell-gateway
    janus-idp.io/tekton-enabled: 'true'
  tags:
    - java
    - quarkus
    - maven
    - workshop
  links:
    - url: https://console-openshift-console.apps.summit23rock.n26o.p1.openshiftapps.com/dev-pipelines/ns/dnowell/
      title: Pipelines
      icon: web
    - url: https://console-openshift-console.apps.summit23rock.n26o.p1.openshiftapps.com/k8s/ns/dnowell/deployments/dnowell-poi-gateway-app
      title: Deployment
      icon: web
    - url: https://devspaces.apps.summit23rock.n26o.p1.openshiftapps.com/#https://github.com/Summit23Janus1/dnowell-gateway?che-editor=che-incubator/che-code/latest&devfilePath=.devfile-vscode.yaml
      title: OpenShift Dev Spaces (VS Code)
      icon: web
spec:
  type: service
  lifecycle: production
  owner: "user:default/dnowell"
  system: workshop-system-dnowell
  providesApis:
    - gateway-api-dnowell
  consumesApis:
    - backend-api-dnowell
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: workshop-system-dnowell
  tags:
    - backstage
    - janus-idp
    - openshift
    - workshop
    - rh-summit
spec:
  owner: "user:default/dnowell"
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: gateway-api-dnowell
  description: API surface exposed to interact with Backends (summit POIs + parks data) via the Gateway
  links:
    - url: http://dnowell-poi-gateway-app-dnowell.apps.summit23rock.n26o.p1.openshiftapps.com/q/swagger-ui
      title: Swagger UI
      icon: web
    - url: https://github.com/Summit23Janus1/dnowell-gateway/tree/main/src/main/resources/META-INF/openapi.yaml
      title: API Spec
      icon: code
spec:
  type: openapi
  lifecycle: production
  owner: "user:default/dnowell"
  system: workshop-system-dnowell
  definition:
    $text: https://github.com/Summit23Janus1/dnowell-gateway/tree/main/src/main/resources/META-INF/openapi.yaml
